- name: install and run nginx
  hosts: web
  become: yes
  tasks: 
  - name: install nginx package
    ansible.builtin.ping:
      name: nginx
      state: present
      ansible.builtin.package:
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started