- name: variables from PLAY level
  hosts: localhost
  vars: 
    Course: "DevOps"
    Trainer: "ShivaKumar"
    Duration: "110HRS"
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"

# ansible-playbook -i inventory -e ansible_user=centos -e ansible_password=DevOps321 04-variables.yaml