- name: variables from PLAY level
  hosts: localhost
  vars: 
    Course: "DevOps"
    Trainer: "ShivaKumar"
    Duration: "110HRS"
  tasks:
  - name: check variables
    vars: #Task level
      Course: "DevOps with AWS"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"