- name: variables from PLAY level
  hosts: localhost
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"

# ansible-playbook -i inventory -e ansible_user=centos -e ansible_password=DevOps321 08-vars-inventory.yaml