- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: print person
    ansible.builtin.package:
      msg: "Hello {{item}}" #item is a default keyword
    loop:
    - git
    - mysql
    - postfix 
    - nodejs
    
